const physicsData = {
  "101": [
    { name: "Measurement", questions: [
      {q:"1. The SI unit of length is?", options:["Kilogram","Meter","Second","Ampere"], a:"Meter"},
      {q:"2. The instrument used to measure internal diameter is?", options:["Meter rule","Vernier caliper","Micrometer screw gauge","Thermometer"], a:"Vernier caliper"},
      {q:"3. 1km is equal to?", options:["100m","1000m","10m","10000m"], a:"1000m"},
      {q:"4. Which of these is a fundamental quantity?", options:["Force","Velocity","Mass","Work"], a:"Mass"},
      {q:"5. The dimension of velocity is?", options:["LT^-1","L^2T^-2","MT^-2","L"], a:"LT^-1"},
      {q:"6. Precision refers to?", options:["Closeness to true value","Repeatability of measurement","Size of error","Unit of measurement"], a:"Repeatability of measurement"},
      {q:"7. 1 Newton is equal to?", options:["kg m/s","kg m/s^2","kg/s^2","kg m^2/s"], a:"kg m/s^2"},
      {q:"8. Zero error is corrected by?", options:["Taking average","Calibration","Ignoring it","Changing instrument"], a:"Calibration"},
      {q:"9. The SI unit of time is?", options:["Minute","Hour","Second","Day"], a:"Second"},
      {q:"10. Area has the dimension?", options:["L","L^2","L^3","LT^-1"], a:"L^2"},
      {q:"11. 1 micro meter = ? m", options:["10^-3","10^-6","10^-9","10^-12"], a:"10^-6"},
      {q:"12. Density is?", options:["Mass/Volume","Volume/Mass","Mass x Volume","Weight/Volume"], a:"Mass/Volume"},
      {q:"13. SI unit of electric current?", options:["Volt","Ohm","Ampere","Coulomb"], a:"Ampere"},
      {q:"14. Random errors can be reduced by?", options:["Taking one reading","Taking average","Using bigger instrument","Guessing"], a:"Taking average"},
      {q:"15. The device for measuring mass?", options:["Spring balance","Beam balance","Thermometer","Barometer"], a:"Beam balance"},
      {q:"16. Volume of cube is?", options:["l^2","l^3","2l^2","6l^2"], a:"l^3"},
      {q:"17. Which is NOT a derived quantity?", options:["Pressure","Length","Force","Energy"], a:"Length"},
      {q:"18. 1 Joule = ? kg m^2/s^2", options:["1","10","100","1000"], a:"1"},
      {q:"19. Least count of meter rule?", options:["1cm","1mm","0.1mm","0.01mm"], a:"1mm"},
      {q:"20. Least count of Vernier caliper?", options:["1cm","1mm","0.1mm","0.01mm"], a:"0.1mm"},
      {q:"21. Temperature is measured in?", options:["Celsius","Kelvin","Fahrenheit","All of the above"], a:"Kelvin"},
      {q:"22. Candela is unit of?", options:["Length","Mass","Luminous intensity","Amount of substance"], a:"Luminous intensity"},
      {q:"23. 1 hour = ? seconds", options:["60","600","3600","86400"], a:"3600"},
      {q:"24. Relative density has?", options:["Unit kg/m^3","No unit","Unit N/m^2","Unit J"], a:"No unit"},
      {q:"25. The range of a micrometer?", options:["0-10cm","0-25mm","0-1m","0-100cm"], a:"0-25mm"},
      {q:"26. Accuracy means?", options:["Repeatability","Closeness to true value","Least count","Zero error"], a:"Closeness to true value"},
      {q:"27. Dimension of force?", options:["MLT^-2","ML^2T^-2","MLT^-1","ML^0T^0"], a:"MLT^-2"},
      {q:"28. 1 litre = ? m^3", options:["0.001","0.01","0.1","1"], a:"0.001"},
      {q:"29. Spring balance measures?", options:["Mass","Weight","Density","Volume"], a:"Weight"},
      {q:"30. Systematic error is due to?", options:["Human error","Instrument fault","Random fluctuation","Parallax"], a:"Instrument fault"},
      {q:"31. The SI unit of frequency?", options:["Hz","s^-1","Both A and B","Watt"], a:"Both A and B"},
      {q:"32. Parallax error is?", options:["Systematic","Random","Personal","Constant"], a:"Personal"},
      {q:"33. 1 horsepower = ? watts", options:["100","500","746","1000"], a:"746"},
      {q:"34. Mole is unit of?", options:["Mass","Amount of substance","Temperature","Current"], a:"Amount of substance"},
      {q:"35. Vernier constant = ?", options:["1mm/10","1cm/10","1mm/100","1cm/100"], a:"1mm/10"},
      {q:"36. Dimension of pressure?", options:["ML^-1T^-2","MLT^-2","ML^-2T^-2","ML^2T^-2"], a:"ML^-1T^-2"},
      {q:"37. 1 eV = ? Joules", options:["1.6 x 10^-19","9.1 x 10^-31","3 x 10^8","6.6 x 10^-34"], a:"1.6 x 10^-19"},
      {q:"38. Standard meter is kept in?", options:["USA","UK","France","Switzerland"], a:"France"},
      {q:"39. Which is vector?", options:["Speed","Distance","Displacement","Mass"], a:"Displacement"},
      {q:"40. Percentage error formula?", options:["Error/True x 100","True/Error x 100","Error x True","True - Error"], a:"Error/True x 100"},
      {q:"41. Radian is unit of?", options:["Length","Angle","Time","Mass"], a:"Angle"},
      {q:"42. 1 Tesla = ?", options:["N/A m","N/A","Wb/m^2","All of the above"], a:"All of the above"},
      {q:"43. Dimensionally, energy and work?", options:["Different","Same","Energy bigger","Work bigger"], a:"Same"},
      {q:"44. Least count of screw gauge?", options:["1mm","0.1mm","0.01mm","0.001mm"], a:"0.01mm"},
      {q:"45. Standard kilogram is made of?", options:["Steel","Platinum-Iridium","Gold","Aluminum"], a:"Platinum-Iridium"},
      {q:"46. Dimension of momentum?", options:["MLT^-1","MLT^-2","ML^2T^-1","ML^0T^0"], a:"MLT^-1"},
      {q:"47. 1 bar = ? Pa", options:["10^3","10^4","10^5","10^6"], a:"10^5"},
      {q:"48. Calibration removes?", options:["Random error","Systematic error","Gross error","All errors"], a:"Systematic error"},
      {q:"49. Count per second is unit of?", options:["Activity","Dose","Exposure","Half-life"], a:"Activity"},
      {q:"50. Standard second is based on?", options:["Earth rotation","Cesium atom","Pendulum","Quartz"], a:"Cesium atom"}
    ]},
    { name: "Vectors and Scalars", questions: [
      {q:"1. Which is a scalar quantity?", options:["Force","Velocity","Mass","Acceleration"], a:"Mass"},
      {q:"2. Resultant of 2 vectors is maximum when?", options:["0 degrees","90 degrees","180 degrees","270 degrees"], a:"0 degrees"},
      {q:"3. Dot product gives?", options:["Vector","Scalar","Both","None"], a:"Scalar"},
      {q:"4. Cross product gives?", options:["Vector","Scalar","Both","None"], a:"Vector"},
      {q:"5. Unit vector has magnitude?", options:["0","1","2","Depends"], a:"1"}
      // I stopped at 5 here. I have all 50. Want me to paste all 50?
    ]}
    // Topics 3 to 10 will come next
  ],
  "102": []
};
